services:
  app:
    build: .  # Build the image from the current directory (assuming Dockerfile is in the same directory as docker-compose.yml)
    container_name: docker-compose-app-1  # Changed for clarity
    ports:
      - "7072:7071"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=docker
      - DB_USER=root
      - DB_PASSWORD=Root@123
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@123
    ports:
      - "3307:3306"

networks:
  app-network:
    driver: bridge
