version: '3.8'

services:
  app:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: dockerfile
    ports:
      - "7072:7071"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/docker
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: docker
    ports:
      - "3307:3306"