version: '3.8'

services:
  app:
    image: docker-compose-app  # Use the image you just built
    container_name: docker-compose-db-1
    ports:
      - "7072:7071"
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Example of environment variables
      - DB_HOST=db  # Database host name (service name)
      - DB_PORT=3306  # MySQL port
      - DB_NAME=docker  # Your DB name
      - DB_USER=root  # DB user
      - DB_PASSWORD=Root@123  # DB password
    depends_on:
      - db  # Make sure the app starts after the DB service is ready
    networks:
      - app-network

  db:
    image: mysql:8.0  # MySQL Docker image
    environment:
      MYSQL_ROOT_PASSWORD: Root@123  # Root password for MySQL
      MYSQL_DATABASE: docker  # The database name to create
      MYSQL_USER: root  # The username for the DB
      MYSQL_PASSWORD: Root@123  # Password for the DB user
    ports:
      - "3307:3306"  # Expose the DB port for external access (if needed)

networks:
  app-network:
    driver: bridge  # Default network type
