version: '3.8'

services:
  app:
    build: .  # Build the image from the current directory (assuming Dockerfile is in the same directory as docker-compose.yml)
    container_name: docker-compose-app-1
    ports:
      - "7072:7071"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=docker
      - DB_USER=root
      - DB_PASSWORD=Root@123
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root@123  # Set root password
      MYSQL_DATABASE: docker  # Default database to create
    ports:
      - "3307:3306"  # Expose DB port to the host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
